language: python
dist: focal
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage

script: cd src && coverage run -m mailtorpedo.tests

after_success:
  - bash <(curl -s https://codecov.io/bash)